name: "Build App"
description: Builds the frontend and Go application
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install frontend dependencies
      working-directory: ./frontend
      shell: bash
      run: npm ci

    - name: Build frontend assets
      working-directory: ./frontend
      shell: bash
      run: npm run build

    - name: Build Go application for Windows
      shell: bash
      run: |
        mkdir -p build/windows
        GOOS=windows GOARCH=amd64 go build -v -o build/windows/switch-library-manager.exe .

    - name: Build Go application for Linux
      shell: bash
      run: |
        mkdir -p build/linux
        GOOS=linux GOARCH=amd64 go build -v -o build/linux/switch-library-manager .

    - name: Build Go application for Mac
      shell: bash
      run: |
        mkdir -p build/darwin
        GOOS=darwin GOARCH=amd64 go build -v -o build/darwin/switch-library-manager .
